### ISSUE TITLE
Python tests fail on OS X python 2.7

### ISSUE THREAD

**Issue by ChrisCummins** [ChrisCummins/clgen#35]
During first install:
```
test_checksum (tests.TestCLgen) ... ok
test_checksum_file (tests.TestCLgen) ... ok
test_checksum_str (tests.TestCLgen) ... ok
test_get_substring_idxs (tests.TestCLgen) ... ok
test_pacakge_data (tests.TestCLgen) ... ok
test_pacakge_str (tests.TestCLgen) ... ok
test_sql_script (tests.TestCLgen) ... ok
test_404 (tests.test_cache.TestCache) ... ok
test_init_and_empty (tests.test_cache.TestCache) ... ok
test_path_escape (tests.test_cache.TestCache) ... ok
test_remove (tests.test_cache.TestCache) ... ok
test_set_and_get (tests.test_cache.TestCache) ... ok
test_build_program (tests.test_cldrive.TestKernelDriver) ... ok
test_call (tests.test_cldrive.TestKernelDriver) ... ok
test_context (tests.test_cldrive.TestKernelDriver) ... ok
test_kernel (tests.test_cldrive.TestKernelDriver) ... ok
test_name (tests.test_cldrive.TestKernelDriver) ... ok
test_non_terminating (tests.test_cldrive.TestKernelDriver) ... SKIP: how long you got?
test_out_of_resources (tests.test_cldrive.TestKernelDriver) ... ok
test_profile (tests.test_cldrive.TestKernelDriver) ... ok
test_prototype (tests.test_cldrive.TestKernelDriver) ... ok
test_source (tests.test_cldrive.TestKernelDriver) ... ok
test_validate (tests.test_cldrive.TestKernelDriver) ... ok
test_validate_input_insensitive (tests.test_cldrive.TestKernelDriver) ... SKIP: FIXME: doesn't pass
test_validate_no_outputs (tests.test_cldrive.TestKernelDriver) ... ok
test_validate_nondeterministic (tests.test_cldrive.TestKernelDriver) ... SKIP: device-dependent
test_comparisons (tests.test_cldrive.TestKernelPayload) ... ok
test_create_random (tests.test_cldrive.TestKernelPayload) ... ok
test_create_sequential (tests.test_cldrive.TestKernelPayload) ... ok
test_arg (tests.test_clutil.TestKernelArg) ... ok
test_arg_is_global (tests.test_clutil.TestKernelArg) ... ok
test_arg_is_local (tests.test_clutil.TestKernelArg) ... ok
test_arg_names (tests.test_clutil.TestKernelArg) ... ok
test_from_source (tests.test_clutil.TestKernelPrototype) ... ok
test_kernel_args (tests.test_clutil.TestKernelPrototype) ... ok
test_kernel_name (tests.test_clutil.TestKernelPrototype) ... ok
test_get_kernel_prototype (tests.test_clutil.TestOpenCLUtil) ... ok
test_strip_attributes (tests.test_clutil.TestOpenCLUtil) ... ok
test_badpath (tests.test_corpus.TestCorpus) ... ok
test_path (tests.test_corpus.TestCorpus) ... ok
test_path_is_archive (tests.test_corpus.TestCorpus) ... ok
test_unpack_archive (tests.test_corpus.TestCorpus) ... ok
test_is_github (tests.test_dbutil.TestDbutil) ... ok
test_table_exists (tests.test_dbutil.TestDbutil) ... ok
test_binaries_exist (tests.test_native.TestNative) ... ok
test_files_exist (tests.test_native.TestNative) ... ok
test_preprocess (tests.test_preprocess.TestPreprocess) ... ok
test_remove_bad_preprocessed (tests.test_preprocess.TestPreprocess) ... ok

----------------------------------------------------------------------
Ran 48 tests in 57.366s

OK (skipped=3)
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 366, in _handle_tasks
    debug('task handler got sentinel')
TypeError: 'NoneType' object is not callable
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 330, in _handle_workers
    debug('worker handler exiting')
TypeError: 'NoneType' object is not callable

Exception TypeError: TypeError("'NoneType' object does not support item deletion",) in <Finalize object, dead> ignored

bash -c   5064.17s user 363.89s system 170% cpu 52:56.46 total
```

Running `sudo make test` doesn't have this problem(!)

**Comment by ChrisCummins** [comment]
Made redundant by #72.
