### ISSUE TITLE
Missing dependency 'libffi' on OpenSuse 12.3

### ISSUE THREAD

**Issue by ChrisCummins** [ChrisCummins/clgen#36]
```
Downloading/unpacking pyopencl==2016.2 (from -r requirements.txt (line 14))
  Downloading pyopencl-2016.2.tar.gz (343kB): 343kB downloaded
  Running setup.py egg_info for package pyopencl
    ---------------------------------------------------------------------------
    Mako is not installed.
    ---------------------------------------------------------------------------
    That is not a problem, as most of PyOpenCL will be just fine
    without it. Some higher-level parts of pyopencl (such as
    pyopencl.reduction) will not function without the templating engine
    Mako [1] being installed. If you would like this functionality to
    work, you might want to install Mako after you finish
    installing PyOpenCL.

    Simply type
    python -m pip install mako
    either now or after the installation completes to fix this.

    [1] http://www.makotemplates.org/
    ---------------------------------------------------------------------------
    Hit Ctrl-C now if you'd like to think about the situation.
    ---------------------------------------------------------------------------
Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
    compilation terminated.

    ---------------------------------------------------------------------------
    Sorry, your build failed. Try rerunning configure.py with different options.
    ---------------------------------------------------------------------------
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-build/pyopencl/setup.py", line 247, in <module>
        main()
      File "/tmp/pip-build/pyopencl/setup.py", line 243, in main
        zip_safe=False)
      File "aksetup_helper.py", line 21, in setup
        setup(*args, **kwargs)
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 221, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 246, in fetch_build_eggs
        replace_conflicting=True
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 596, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 841, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 853, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 296, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 598, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 628, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 823, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1103, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1091, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1
    Complete output from command python setup.py egg_info:
    ---------------------------------------------------------------------------

Mako is not installed.

---------------------------------------------------------------------------

That is not a problem, as most of PyOpenCL will be just fine
No package 'libffi' found

c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory

compilation terminated.



---------------------------------------------------------------------------

Sorry, your build failed. Try rerunning configure.py with different options.

---------------------------------------------------------------------------

Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-build/pyopencl/setup.py", line 247, in <module>

    main()

  File "/tmp/pip-build/pyopencl/setup.py", line 243, in main

    zip_safe=False)

  File "aksetup_helper.py", line 21, in setup

    setup(*args, **kwargs)

  File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 221, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 246, in fetch_build_eggs

    replace_conflicting=True

  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 596, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 841, in best_match

    return self.obtain(req, installer) # try and download/install

  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 853, in obtain

    return installer(requirement)

  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 296, in fetch_build_egg

    return cmd.easy_install(req)

  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 598, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 628, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 823, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1103, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1091, in run_setup

    raise DistutilsError("Setup script exited with %s" % (v.args[0],))

distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build/pyopencl
Storing complete log in /root/.pip/pip.log
make: *** [install] Error 1
sudo -H make install  61.65s user 3.19s system 81% cpu 1:19.14 total
```

**Comment by ChrisCummins** [comment]
documented
