### ISSUE TITLE
preprocess: Too many processes causes out of memory error

### ISSUE THREAD

**Issue by ChrisCummins** [ChrisCummins/clgen#64]
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./inference.py", line 95, in <module>
  File "./inference.py", line 90, in main
    clgen.write_file(outpath, clgen.format_json(info))
  File "./inference.py", line 31, in evaluate
    num_good_kernels = dbutil.num_good_kernels(sample_db)
  File "/home/cec/clgen/lib/python3.5/site-packages/CLgen-0.2.1-py3.5.egg/clgen/preprocess.py", line 763, in preprocess_db
    preprocess_contentfiles(db_path)
  File "/home/cec/clgen/lib/python3.5/site-packages/CLgen-0.2.1-py3.5.egg/clgen/preprocess.py", line 698, in preprocess_contentfiles
    raise e
  File "/home/cec/clgen/lib/python3.5/site-packages/CLgen-0.2.1-py3.5.egg/clgen/preprocess.py", line 695, in preprocess_contentfiles
    pool.map(_preprocess_db_worker, jobs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
OSError: [Errno 12] Cannot allocate memory
```

**Comment by ChrisCummins** [comment]
fixed
